name: Develop merge
on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      SHA6: ${GITHUB_SHA::6}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6

      - uses: JS-DevTools/npm-publish@v1
        with:
          tag: ${{ steps.package-version.outputs.current-version}}.beta.${{ steps.short-sha.outputs.sha }}
          token: ${{ secrets.NPM_TOKEN }}